# Use an official Python runtime as a parent image
FROM python:3.10.13

# Install Git
RUN apt-get update && apt-get install -y git

# Set the working directory in the container
WORKDIR /usr/src/app

# Clone the necessary GitHub repositories
RUN for i in {1..5}; do git clone https://github.com/arnmamel/security-analysis-api.git && break || sleep 5; done
RUN for i in {1..5}; do git clone https://github.com/arnmamel/nlp-gym.git && break || sleep 5; done

# Install dependencies from the first repository
WORKDIR /usr/src/app/security-analysis-api
RUN pip install --no-cache-dir -r requirements.txt

# Expose the necessary ports
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
